### ISSUE TITLE
[Feature] Create Dummy Class Under Appropriate Namespace

### ISSUE THREAD

**Issue by steviegt6** [rejuvena/collate#2]
We should not need to do this: https://github.com/rejuvena/collate/blob/master/src/Rejuvena.Collate.ExampleMod/Rejuvena.Collate.ExampleMod.csproj#L15

tModLoader requires that at least one loadable (as in JIT-able, not `ILoadable`-implementing), as per https://github.com/tModLoader/tModLoader/blob/58794a48d27a7d2babb7760dd33cbcfe5068305f/patches/tModLoader/Terraria/ModLoader/Core/AssemblyManager.cs#L213. A fix manually implemented by a modder looks like this:
![image](https://user-images.githubusercontent.com/27323911/188539791-e20f75eb-51ed-4fad-a9fd-85e68c6afd0c.png)

It is incredibly simple to replicate this fix with a simple post-compilation patch. We should do that.

**Comment by Tabizzz** [comment]
is it possible to do that if in my mod I don't have a class in the namespace of the mod, collate add the dummy automatically?, like creating the class in the obj directory

**Comment by steviegt6** [comment]
> is it possible to do that if in my mod I don't have a class in the namespace of the mod, collate add the dummy automatically?, like creating the class in the obj directory

That is what this issue proposes (not creating any files tho, just editing the type into the assembly).

**Comment by steviegt6** [comment]
Implemented in 480b2af7f30dd4483d174b5f4a134b2aab802277.
